AWSTemplateFormatVersion : 2010-09-09
Description : This template creates basic Infrastructure 
Metadata : {}
Conditions : {}
Parameters :
    Environment :
        Description: Select the stage of project.
        Type : String
        AllowedValues :
            - dev
            - qa
            - prod
    InstanceType :
        Description : Select intance type based on your project
        Type : String
        AllowedValues :
          - t1.micro
          - t2.2xlarge
          - t2.large 
          - t2.medium
          - t2.micro 
          - t2.nano 
          - t2.small 
          - t2.xlarge 
    SubnetCidr :
        Description : Subenet Cidr range for subnets
        Type: String
        AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
        ConstraintDescription: CidrBlock must be in the form of x.x.x.x/16-24
    SubnetCidr1 :
        Description : Subenet Cidr range for subnets
        Type: String
        AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
        ConstraintDescription: CidrBlock must be in the form of x.x.x.x/16-24
Resources:
    
    Subnet :
        Type : AWS::EC2::Subnet
        Properties : 
            VpcId : vpc-02c1964a97a4b2b1d
            CidrBlock : 
                Ref: SubnetCidr
            AvailabilityZone : us-east-1a
            MapPublicIpOnLaunch: true
            Tags : 
             -  Key : Name
                Value : PublicSubnet   
                
    Subnet1 : 
        Type : AWS::EC2::Subnet
        Properties :
            VpcId : vpc-02c1964a97a4b2b1d                
            CidrBlock : 
                Ref : SubnetCidr1
            AvailabilityZone : us-east-1b
            Tags :
             -  Key : Name
                Value : PrivateSubnet
    InternetGateway : 
        Type : AWS::EC2::InternetGateway
        Properties : 
            Tags : 
             -  Key : Name
                Value : IGW
    ElasticIpAddress :
        Type : AWS::EC2::EIP
        DependsOn : InternetGateway
        Properties :
            Domain : vpc
    NatGateway : 
        Type : AWS::EC2::NatGateway
        Properties :
            AllocationId : !GetAtt ElasticIpAddress.AllocationId
            SubnetId : 
                Ref : Subnet
                
    AttachGateway : 
        Type : AWS::EC2::VPCGatewayAttachment
        Properties :
            VpcId : vpc-02c1964a97a4b2b1d
            InternetGatewayId : 
                Ref : InternetGateway 
    
    NatRouteTable :
        Type : AWS::EC2::RouteTable
        Properties : 
            VpcId : vpc-02c1964a97a4b2b1d
            Tags :
              - Key : Name
                Value : NatRouteTable                
    NatRoute :
        Type : AWS::EC2::Route
        DependsOn : NatGateway
        Properties :
            RouteTableId : 
                Ref : NatRouteTable
            NatGatewayId : 
                Ref : NatGateway
            DestinationCidrBlock : 0.0.0.0/0
    Route : 
        Type : AWS::EC2::Route
        DependsOn : InternetGateway
        Properties :
            RouteTableId : rtb-07ea962a45961122f
            GatewayId : 
                Ref : InternetGateway
            DestinationCidrBlock : 0.0.0.0/0   
            
    SubnetRouteTableAssociation : 
        Type : AWS::EC2::SubnetRouteTableAssociation
        Properties :
            RouteTableId :  rtb-07ea962a45961122f
            SubnetId : 
                Ref : Subnet
    
    SubnetNatTableAssociation : 
        Type : AWS::EC2::SubnetRouteTableAssociation
        Properties :
            RouteTableId : 
                Ref : NatRouteTable

            SubnetId : 
                Ref : Subnet1
          
    PublicWebServer :
        Type : AWS::EC2::Instance
        Properties :
            ImageId : ami-00874d747dde814fa
            InstanceType : 
                Ref : InstanceType
            KeyName : ubuntujp
            Monitoring: true
            SecurityGroupIds: 
                - sg-085b328f51b875922
            SubnetId: 
                Ref : Subnet
            UserData :
              Fn::Base64: !Sub |
                  #!/bin/bash -xe
                  sudo apt update -y
                  sudo apt install nginx -y
                  sudo systemctl start nginx.service
                  sudo systemctl enable nginx
            Tags :
              - Key : Name
                Value : NginxServer
              - Key : stack
                Value : Dev
    
    PrivateWebServer :
        Type : AWS::EC2::Instance
        Properties :
            ImageId : ami-00874d747dde814fa
            InstanceType : 
                Ref : InstanceType
            KeyName : ubuntujp
            Monitoring: true
            SecurityGroupIds: 
                - sg-085b328f51b875922
            SubnetId: 
                Ref : Subnet1
            UserData :
              Fn::Base64: !Sub |
                  #!/bin/bash -xe
                  sudo apt update
                  sudo apt install httpd -y
                  sudo systemctl start httpd.service
                  sudo systemctl enable httpd
            Tags :
              - Key : Name
                Value : HttpdServer
              - Key : stack
                Value : Dev2
            
            

Outputs : 
            
    Subnet :
        Description : Id of subnet
        Value : 
            Ref : Subnet
            
    Subnet1 :
        Description : id of subnet
        Value : 
            Ref : Subnet1
            

