AWSTemplateFormatVersion: 2010-09-09
Description: This template creates basic Infrastructure
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - qa
      - prod
  VpcEx:
    Type: String
    Description: VpcId
    Default: vpc-046ce5f986265e8cd
  Subnet1:
    Type: String
    Description: Subnet1
    Default: subnet-02fdb95a1d6a548eb
  Subnet2:
    Type: String
    Description: Subnet1
    Default: subnet-085059141bb58cc95 
  SecurityGroup:
    Type: String
    Description: sg for stack
    Default: sg-04f0dcd0c13560349
Resources:
  
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0557a15b87f6559cf
      InstanceType: t2.micro
      KeyName: newkp
      NetworkInterfaces :
        -  AssociatePublicIpAddress : true
           DeviceIndex : 0
           DeleteOnTermination : true
           SubnetId :  
              Ref : Subnet1
                   
           GroupSet : 
             - sg-04f0dcd0c13560349

      UserData :
        Fn::Base64: !Sub |
            #!/bin/bash -xe
            sudo yum update -y
            sudo amazon-linux-extras install nginx1 -y
            sudo systemctl start nginx
            sudo systemctl enable nginx

Outputs:
  VPCId:
    Description: Vpc of the Default VPC
    Value:
      Ref: VpcEx

  Subnet1:
    Description: Id of subnet
    Value:
      Ref: Subnet1

  Subnet2:
    Description: id of subnet
    Value:
      Ref: Subnet2
