

AWSTemplateFormatVersion : 2010-09-09
Description : This template creates basic Infrastructure
Metadata : {}
Conditions : {}
Parameters :
    Environment :
        Description: Select the stage of project.
        Type : String
        AllowedValues :
            - dev
            - qa
            - prod
    InstanceType :
        Description : Select intance type based on your project
        Type : String
        AllowedValues :
          - t1.micro
          - t2.2xlarge
          - t2.large
          - t2.medium
          - t2.micro
          - t2.nano
          - t2.small
          - t2.xlarge
    SubnetCidr :
        Description : Subenet Cidr range for subnets
        Type: String
        AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
        ConstraintDescription: CidrBlock must be in the form of x.x.x.x/16-24
    SubnetCidr1 :
        Description : Subenet Cidr range for subnets
        Type: String
        AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
        ConstraintDescription: CidrBlock must be in the form of x.x.x.x/16-24
Resources:

    Subnet :
        Type : AWS::EC2::Subnet
        Properties :
            VpcId : vpc-02c1964a97a4b2b1d
            CidrBlock :
                Ref: SubnetCidr
            AvailabilityZone : us-east-1a
            MapPublicIpOnLaunch: true
            Tags :
             -  Key : Name
bastionserver.yml [dos] (12:18 03/02/2023)                                                                                                                                             1,0-1 Top


